replicaCount: 2

image:
  repository: sandeeppaul/my-repo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  hosts:
    - host: my-app.35.198.238.24.nip.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-app
              port:
                number: 80
  tls: []  # configure if TLS is required